//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `ServerSide.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ServerSide;

public interface Mp3filesManagerPrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean ajouterMorceauMp3(String title, String Auteur, String path)
    {
        return ajouterMorceauMp3(title, Auteur, path, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean ajouterMorceauMp3(String title, String Auteur, String path, java.util.Map<String, String> context)
    {
        return _iceI_ajouterMorceauMp3Async(title, Auteur, path, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> ajouterMorceauMp3Async(String title, String Auteur, String path)
    {
        return _iceI_ajouterMorceauMp3Async(title, Auteur, path, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> ajouterMorceauMp3Async(String title, String Auteur, String path, java.util.Map<String, String> context)
    {
        return _iceI_ajouterMorceauMp3Async(title, Auteur, path, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_Auteur -
     * @param iceP_path -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_ajouterMorceauMp3Async(String iceP_title, String iceP_Auteur, String iceP_path, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ajouterMorceauMp3", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_Auteur);
                     ostr.writeString(iceP_path);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean supprimerMorceauMp3(String title, String path)
    {
        return supprimerMorceauMp3(title, path, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean supprimerMorceauMp3(String title, String path, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauMp3Async(title, path, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> supprimerMorceauMp3Async(String title, String path)
    {
        return _iceI_supprimerMorceauMp3Async(title, path, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> supprimerMorceauMp3Async(String title, String path, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauMp3Async(title, path, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_path -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_supprimerMorceauMp3Async(String iceP_title, String iceP_path, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimerMorceauMp3", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_path);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean modifierMorceauMp3(String title, String Auteur, String newtitle)
    {
        return modifierMorceauMp3(title, Auteur, newtitle, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean modifierMorceauMp3(String title, String Auteur, String newtitle, java.util.Map<String, String> context)
    {
        return _iceI_modifierMorceauMp3Async(title, Auteur, newtitle, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> modifierMorceauMp3Async(String title, String Auteur, String newtitle)
    {
        return _iceI_modifierMorceauMp3Async(title, Auteur, newtitle, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> modifierMorceauMp3Async(String title, String Auteur, String newtitle, java.util.Map<String, String> context)
    {
        return _iceI_modifierMorceauMp3Async(title, Auteur, newtitle, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_Auteur -
     * @param iceP_newtitle -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_modifierMorceauMp3Async(String iceP_title, String iceP_Auteur, String iceP_newtitle, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "modifierMorceauMp3", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_Auteur);
                     ostr.writeString(iceP_newtitle);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default String findByTitreAuteur(String title, String Auteur)
    {
        return findByTitreAuteur(title, Auteur, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String findByTitreAuteur(String title, String Auteur, java.util.Map<String, String> context)
    {
        return _iceI_findByTitreAuteurAsync(title, Auteur, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> findByTitreAuteurAsync(String title, String Auteur)
    {
        return _iceI_findByTitreAuteurAsync(title, Auteur, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> findByTitreAuteurAsync(String title, String Auteur, java.util.Map<String, String> context)
    {
        return _iceI_findByTitreAuteurAsync(title, Auteur, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_Auteur -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_findByTitreAuteurAsync(String iceP_title, String iceP_Auteur, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByTitreAuteur", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_Auteur);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static Mp3filesManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), Mp3filesManagerPrx.class, _Mp3filesManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static Mp3filesManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), Mp3filesManagerPrx.class, _Mp3filesManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static Mp3filesManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), Mp3filesManagerPrx.class, _Mp3filesManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static Mp3filesManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), Mp3filesManagerPrx.class, _Mp3filesManagerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static Mp3filesManagerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, Mp3filesManagerPrx.class, _Mp3filesManagerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static Mp3filesManagerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, Mp3filesManagerPrx.class, _Mp3filesManagerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default Mp3filesManagerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (Mp3filesManagerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default Mp3filesManagerPrx ice_adapterId(String newAdapterId)
    {
        return (Mp3filesManagerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default Mp3filesManagerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (Mp3filesManagerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default Mp3filesManagerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (Mp3filesManagerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default Mp3filesManagerPrx ice_invocationTimeout(int newTimeout)
    {
        return (Mp3filesManagerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default Mp3filesManagerPrx ice_connectionCached(boolean newCache)
    {
        return (Mp3filesManagerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default Mp3filesManagerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (Mp3filesManagerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default Mp3filesManagerPrx ice_secure(boolean b)
    {
        return (Mp3filesManagerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default Mp3filesManagerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (Mp3filesManagerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default Mp3filesManagerPrx ice_preferSecure(boolean b)
    {
        return (Mp3filesManagerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default Mp3filesManagerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (Mp3filesManagerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default Mp3filesManagerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (Mp3filesManagerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default Mp3filesManagerPrx ice_collocationOptimized(boolean b)
    {
        return (Mp3filesManagerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default Mp3filesManagerPrx ice_twoway()
    {
        return (Mp3filesManagerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default Mp3filesManagerPrx ice_oneway()
    {
        return (Mp3filesManagerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default Mp3filesManagerPrx ice_batchOneway()
    {
        return (Mp3filesManagerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default Mp3filesManagerPrx ice_datagram()
    {
        return (Mp3filesManagerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default Mp3filesManagerPrx ice_batchDatagram()
    {
        return (Mp3filesManagerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default Mp3filesManagerPrx ice_compress(boolean co)
    {
        return (Mp3filesManagerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default Mp3filesManagerPrx ice_timeout(int t)
    {
        return (Mp3filesManagerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default Mp3filesManagerPrx ice_connectionId(String connectionId)
    {
        return (Mp3filesManagerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    default Mp3filesManagerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (Mp3filesManagerPrx)ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ServerSide::Mp3filesManager";
    }
}
