//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `MorceauManager.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MorceauManager;

/** @hidden */
public class _Mp3filesManagerPrxI extends com.zeroc.Ice._ObjectPrxI implements Mp3filesManagerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
